baseurl = "https://gg4acrossover.github.io/hugosite/"
copyright = "All rights reserved - 2016"
disqusshortname = "gg4acrossover"
enableEmoji = true
languagecode = "vi-EN"
paginate = 6
pluralizelisttitles = false
theme = "casper-two"
title = "VietHQ"
googleAnalytics = "UA-99127158-1"
[[menu.main]]
identifier = "blog"
name = "Home"
pre = "<h4>My Site</h4>"
url = "/"
weight = -120
[[menu.main]]
name = "Github"
pre = "<h4>Social</h4>"
url = "https://github.com/gg4acrossover"
weight = 100
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/viet142"
weight = 101
[params]
  title       = "VietHQ"
  subtitle    = "Tìm đơn giản trong phức tạp"

  cover       = ""
  description = "VietHQ - Tìm đơn giản trong phức tạp"
  metaDescription = ""
  googleAnalytics = "UA-99127158-1"
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = ""

  logo = ""
  orgName = "viethq"
  orgWebsite = "https://gg4acrossover.github.io/hugosite/"
  orgDescription = "VietHQ - Tìm đơn giản trong phức tạp"

  author = "viethq"
  authorAvatar = ""
  authorLocation = "VietNam"
  authorWebsite = "https://github.com/gg4acrossover"
  authorDescription = "VietHQ - Tìm đơn giản trong phức tạp"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
